name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Récupérer le code source
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Mettre en cache le dépôt Maven (~/.m2) pour accélérer les builds
    - name: Cache Maven local repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

    # 3. Installer Java (vers. 11 ou 17 selon ton POM)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'

    # 4. Compiler et exécuter les tests
    - name: Build with Maven and run tests
      run: mvn --batch-mode clean test

    # 5. Publier les rapports de tests (JUnit XML)
    - name: Archive test reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: junit-reports
        path: target/surefire-reports/*.xml
